//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.08 at 02:30:35 PM CDT 
//


package com.kp.contenttemplate.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for BasicContentItemEditor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicContentItemEditor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="GroupLabel" type="{http://endeca.com/schema/content-template/2008}GroupLabel"/>
 *           &lt;element name="StringEditor" type="{http://endeca.com/schema/content-template/2008}StringEditor"/>
 *           &lt;element name="RecordSelector" type="{http://endeca.com/schema/content-template/2008}RecordSelector"/>
 *           &lt;element name="ComboBox" type="{http://endeca.com/schema/content-template/2008}ComboBox"/>
 *           &lt;element name="CheckBox" type="{http://endeca.com/schema/content-template/2008}CheckBox"/>
 *           &lt;element name="ImagePreview" type="{http://endeca.com/schema/content-template/2008}ImagePreview"/>
 *           &lt;element name="NavigationRecordsEditor" type="{http://endeca.com/schema/content-template/2008}NavigationRecordsEditor"/>
 *           &lt;element name="NavigationRefinementsSelector" type="{http://endeca.com/schema/content-template/2008}NavigationRefinementsSelector"/>
 *           &lt;any processContents='lax' namespace='##other'/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicContentItemEditor", propOrder = {
    "groupLabelOrStringEditorOrRecordSelector"
})
public class BasicContentItemEditor {

    @XmlElementRefs({
        @XmlElementRef(name = "GroupLabel", namespace = "http://endeca.com/schema/content-template/2008", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CheckBox", namespace = "http://endeca.com/schema/content-template/2008", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NavigationRefinementsSelector", namespace = "http://endeca.com/schema/content-template/2008", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ImagePreview", namespace = "http://endeca.com/schema/content-template/2008", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NavigationRecordsEditor", namespace = "http://endeca.com/schema/content-template/2008", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RecordSelector", namespace = "http://endeca.com/schema/content-template/2008", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ComboBox", namespace = "http://endeca.com/schema/content-template/2008", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "StringEditor", namespace = "http://endeca.com/schema/content-template/2008", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> groupLabelOrStringEditorOrRecordSelector;

    /**
     * Gets the value of the groupLabelOrStringEditorOrRecordSelector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupLabelOrStringEditorOrRecordSelector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupLabelOrStringEditorOrRecordSelector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link GroupLabel }{@code >}
     * {@link JAXBElement }{@code <}{@link CheckBox }{@code >}
     * {@link JAXBElement }{@code <}{@link NavigationRefinementsSelector }{@code >}
     * {@link JAXBElement }{@code <}{@link ImagePreview }{@code >}
     * {@link JAXBElement }{@code <}{@link NavigationRecordsEditor }{@code >}
     * {@link JAXBElement }{@code <}{@link RecordSelector }{@code >}
     * {@link Object }
     * {@link JAXBElement }{@code <}{@link ComboBox }{@code >}
     * {@link Element }
     * {@link JAXBElement }{@code <}{@link StringEditor }{@code >}
     * 
     * 
     */
    public List<Object> getGroupLabelOrStringEditorOrRecordSelector() {
        if (groupLabelOrStringEditorOrRecordSelector == null) {
            groupLabelOrStringEditorOrRecordSelector = new ArrayList<Object>();
        }
        return this.groupLabelOrStringEditorOrRecordSelector;
    }

}
