//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.08 at 02:30:35 PM CDT 
//


package com.kp.contenttemplate.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EditorPanel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EditorPanel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="BasicContentItemEditor" type="{http://endeca.com/schema/content-template/2008}BasicContentItemEditor"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EditorPanel", propOrder = {
    "basicContentItemEditor"
})
public class EditorPanel {

    @XmlElement(name = "BasicContentItemEditor")
    protected BasicContentItemEditor basicContentItemEditor;

    /**
     * Gets the value of the basicContentItemEditor property.
     * 
     * @return
     *     possible object is
     *     {@link BasicContentItemEditor }
     *     
     */
    public BasicContentItemEditor getBasicContentItemEditor() {
        return basicContentItemEditor;
    }

    /**
     * Sets the value of the basicContentItemEditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicContentItemEditor }
     *     
     */
    public void setBasicContentItemEditor(BasicContentItemEditor value) {
        this.basicContentItemEditor = value;
    }

}
