//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.08 at 02:30:35 PM CDT 
//


package com.kp.contenttemplate.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kp.contenttemplate.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContentTemplate_QNAME = new QName("http://endeca.com/schema/content-template/2008", "ContentTemplate");
    private final static QName _BasicContentItemEditorGroupLabel_QNAME = new QName("http://endeca.com/schema/content-template/2008", "GroupLabel");
    private final static QName _BasicContentItemEditorNavigationRefinementsSelector_QNAME = new QName("http://endeca.com/schema/content-template/2008", "NavigationRefinementsSelector");
    private final static QName _BasicContentItemEditorRecordSelector_QNAME = new QName("http://endeca.com/schema/content-template/2008", "RecordSelector");
    private final static QName _BasicContentItemEditorStringEditor_QNAME = new QName("http://endeca.com/schema/content-template/2008", "StringEditor");
    private final static QName _BasicContentItemEditorImagePreview_QNAME = new QName("http://endeca.com/schema/content-template/2008", "ImagePreview");
    private final static QName _BasicContentItemEditorComboBox_QNAME = new QName("http://endeca.com/schema/content-template/2008", "ComboBox");
    private final static QName _BasicContentItemEditorCheckBox_QNAME = new QName("http://endeca.com/schema/content-template/2008", "CheckBox");
    private final static QName _BasicContentItemEditorNavigationRecordsEditor_QNAME = new QName("http://endeca.com/schema/content-template/2008", "NavigationRecordsEditor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kp.contenttemplate.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContentTemplate }
     * 
     */
    public ContentTemplate createContentTemplate() {
        return new ContentTemplate();
    }

    /**
     * Create an instance of {@link RuleProperty }
     * 
     */
    public RuleProperty createRuleProperty() {
        return new RuleProperty();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link NavigationRefinementsSelector }
     * 
     */
    public NavigationRefinementsSelector createNavigationRefinementsSelector() {
        return new NavigationRefinementsSelector();
    }

    /**
     * Create an instance of {@link SortChoices }
     * 
     */
    public SortChoices createSortChoices() {
        return new SortChoices();
    }

    /**
     * Create an instance of {@link ContentItemRefList }
     * 
     */
    public ContentItemRefList createContentItemRefList() {
        return new ContentItemRefList();
    }

    /**
     * Create an instance of {@link RecordSelector }
     * 
     */
    public RecordSelector createRecordSelector() {
        return new RecordSelector();
    }

    /**
     * Create an instance of {@link DimensionList }
     * 
     */
    public DimensionList createDimensionList() {
        return new DimensionList();
    }

    /**
     * Create an instance of {@link Sort }
     * 
     */
    public Sort createSort() {
        return new Sort();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link BasicContentItemEditor }
     * 
     */
    public BasicContentItemEditor createBasicContentItemEditor() {
        return new BasicContentItemEditor();
    }

    /**
     * Create an instance of {@link NavigationRecordsEditor }
     * 
     */
    public NavigationRecordsEditor createNavigationRecordsEditor() {
        return new NavigationRecordsEditor();
    }

    /**
     * Create an instance of {@link RelevanceRankingChoices }
     * 
     */
    public RelevanceRankingChoices createRelevanceRankingChoices() {
        return new RelevanceRankingChoices();
    }

    /**
     * Create an instance of {@link ComboBox }
     * 
     */
    public ComboBox createComboBox() {
        return new ComboBox();
    }

    /**
     * Create an instance of {@link EditorPanel }
     * 
     */
    public EditorPanel createEditorPanel() {
        return new EditorPanel();
    }

    /**
     * Create an instance of {@link SortChoice }
     * 
     */
    public SortChoice createSortChoice() {
        return new SortChoice();
    }

    /**
     * Create an instance of {@link StringEditor }
     * 
     */
    public StringEditor createStringEditor() {
        return new StringEditor();
    }

    /**
     * Create an instance of {@link RecordsPerPage }
     * 
     */
    public RecordsPerPage createRecordsPerPage() {
        return new RecordsPerPage();
    }

    /**
     * Create an instance of {@link ContentItemRef }
     * 
     */
    public ContentItemRef createContentItemRef() {
        return new ContentItemRef();
    }

    /**
     * Create an instance of {@link ImagePreview }
     * 
     */
    public ImagePreview createImagePreview() {
        return new ImagePreview();
    }

    /**
     * Create an instance of {@link RecordList }
     * 
     */
    public RecordList createRecordList() {
        return new RecordList();
    }

    /**
     * Create an instance of {@link ComboBoxItem }
     * 
     */
    public ComboBoxItem createComboBoxItem() {
        return new ComboBoxItem();
    }

    /**
     * Create an instance of {@link CheckBox }
     * 
     */
    public CheckBox createCheckBox() {
        return new CheckBox();
    }

    /**
     * Create an instance of {@link RelevanceRankingChoice }
     * 
     */
    public RelevanceRankingChoice createRelevanceRankingChoice() {
        return new RelevanceRankingChoice();
    }

    /**
     * Create an instance of {@link PreviewProperty }
     * 
     */
    public PreviewProperty createPreviewProperty() {
        return new PreviewProperty();
    }

    /**
     * Create an instance of {@link GroupLabel }
     * 
     */
    public GroupLabel createGroupLabel() {
        return new GroupLabel();
    }

    /**
     * Create an instance of {@link RuleInfo }
     * 
     */
    public RuleInfo createRuleInfo() {
        return new RuleInfo();
    }

    /**
     * Create an instance of {@link ContentItem }
     * 
     */
    public ContentItem createContentItem() {
        return new ContentItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "ContentTemplate")
    public JAXBElement<ContentTemplate> createContentTemplate(ContentTemplate value) {
        return new JAXBElement<ContentTemplate>(_ContentTemplate_QNAME, ContentTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupLabel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "GroupLabel", scope = BasicContentItemEditor.class)
    public JAXBElement<GroupLabel> createBasicContentItemEditorGroupLabel(GroupLabel value) {
        return new JAXBElement<GroupLabel>(_BasicContentItemEditorGroupLabel_QNAME, GroupLabel.class, BasicContentItemEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NavigationRefinementsSelector }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "NavigationRefinementsSelector", scope = BasicContentItemEditor.class)
    public JAXBElement<NavigationRefinementsSelector> createBasicContentItemEditorNavigationRefinementsSelector(NavigationRefinementsSelector value) {
        return new JAXBElement<NavigationRefinementsSelector>(_BasicContentItemEditorNavigationRefinementsSelector_QNAME, NavigationRefinementsSelector.class, BasicContentItemEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordSelector }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "RecordSelector", scope = BasicContentItemEditor.class)
    public JAXBElement<RecordSelector> createBasicContentItemEditorRecordSelector(RecordSelector value) {
        return new JAXBElement<RecordSelector>(_BasicContentItemEditorRecordSelector_QNAME, RecordSelector.class, BasicContentItemEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringEditor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "StringEditor", scope = BasicContentItemEditor.class)
    public JAXBElement<StringEditor> createBasicContentItemEditorStringEditor(StringEditor value) {
        return new JAXBElement<StringEditor>(_BasicContentItemEditorStringEditor_QNAME, StringEditor.class, BasicContentItemEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImagePreview }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "ImagePreview", scope = BasicContentItemEditor.class)
    public JAXBElement<ImagePreview> createBasicContentItemEditorImagePreview(ImagePreview value) {
        return new JAXBElement<ImagePreview>(_BasicContentItemEditorImagePreview_QNAME, ImagePreview.class, BasicContentItemEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComboBox }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "ComboBox", scope = BasicContentItemEditor.class)
    public JAXBElement<ComboBox> createBasicContentItemEditorComboBox(ComboBox value) {
        return new JAXBElement<ComboBox>(_BasicContentItemEditorComboBox_QNAME, ComboBox.class, BasicContentItemEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckBox }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "CheckBox", scope = BasicContentItemEditor.class)
    public JAXBElement<CheckBox> createBasicContentItemEditorCheckBox(CheckBox value) {
        return new JAXBElement<CheckBox>(_BasicContentItemEditorCheckBox_QNAME, CheckBox.class, BasicContentItemEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NavigationRecordsEditor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content-template/2008", name = "NavigationRecordsEditor", scope = BasicContentItemEditor.class)
    public JAXBElement<NavigationRecordsEditor> createBasicContentItemEditorNavigationRecordsEditor(NavigationRecordsEditor value) {
        return new JAXBElement<NavigationRecordsEditor>(_BasicContentItemEditorNavigationRecordsEditor_QNAME, NavigationRecordsEditor.class, BasicContentItemEditor.class, value);
    }

}
