//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.08 at 02:30:35 PM CDT 
//


package com.kp.contenttemplate.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * <p>Java class for Property complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Property">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="String" type="{http://endeca.com/schema/content-template/2008}String"/>
 *         &lt;element name="Boolean" type="{http://endeca.com/schema/content-template/2008}String"/>
 *         &lt;element name="RecordList" type="{http://endeca.com/schema/content-template/2008}RecordList"/>
 *         &lt;element name="ContentItem" type="{http://endeca.com/schema/content-template/2008}ContentItemRef"/>
 *         &lt;element name="ContentItemList" type="{http://endeca.com/schema/content-template/2008}ContentItemRefList"/>
 *         &lt;any processContents='lax' namespace='##other'/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Property", propOrder = {
    "string",
    "_boolean",
    "recordList",
    "contentItem",
    "contentItemList",
    "any"
})
public class Property {

    @XmlElement(name = "String")
    protected com.kp.contenttemplate.beans.String string;
    @XmlElement(name = "Boolean")
    protected com.kp.contenttemplate.beans.String _boolean;
    @XmlElement(name = "RecordList")
    protected RecordList recordList;
    @XmlElement(name = "ContentItem")
    protected ContentItemRef contentItem;
    @XmlElement(name = "ContentItemList")
    protected ContentItemRefList contentItemList;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "Name")
    protected java.lang.String name;

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link com.kp.contenttemplate.beans.String }
     *     
     */
    public com.kp.contenttemplate.beans.String getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.kp.contenttemplate.beans.String }
     *     
     */
    public void setString(com.kp.contenttemplate.beans.String value) {
        this.string = value;
    }

    /**
     * Gets the value of the boolean property.
     * 
     * @return
     *     possible object is
     *     {@link com.kp.contenttemplate.beans.String }
     *     
     */
    public com.kp.contenttemplate.beans.String getBoolean() {
        return _boolean;
    }

    /**
     * Sets the value of the boolean property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.kp.contenttemplate.beans.String }
     *     
     */
    public void setBoolean(com.kp.contenttemplate.beans.String value) {
        this._boolean = value;
    }

    /**
     * Gets the value of the recordList property.
     * 
     * @return
     *     possible object is
     *     {@link RecordList }
     *     
     */
    public RecordList getRecordList() {
        return recordList;
    }

    /**
     * Sets the value of the recordList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordList }
     *     
     */
    public void setRecordList(RecordList value) {
        this.recordList = value;
    }

    /**
     * Gets the value of the contentItem property.
     * 
     * @return
     *     possible object is
     *     {@link ContentItemRef }
     *     
     */
    public ContentItemRef getContentItem() {
        return contentItem;
    }

    /**
     * Sets the value of the contentItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentItemRef }
     *     
     */
    public void setContentItem(ContentItemRef value) {
        this.contentItem = value;
    }

    /**
     * Gets the value of the contentItemList property.
     * 
     * @return
     *     possible object is
     *     {@link ContentItemRefList }
     *     
     */
    public ContentItemRefList getContentItemList() {
        return contentItemList;
    }

    /**
     * Sets the value of the contentItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentItemRefList }
     *     
     */
    public void setContentItemList(ContentItemRefList value) {
        this.contentItemList = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

}
