//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.17 at 02:15:09 PM CDT 
//


package com.kp.content.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kp.content.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContentItem_QNAME = new QName("http://endeca.com/schema/content/2008", "ContentItem");
    private final static QName _PropertyRecordList_QNAME = new QName("http://endeca.com/schema/content/2008", "RecordList");
    private final static QName _PropertyString_QNAME = new QName("http://endeca.com/schema/content/2008", "String");
    private final static QName _PropertyContentItemList_QNAME = new QName("http://endeca.com/schema/content/2008", "ContentItemList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kp.content.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContentItem }
     * 
     */
    public ContentItem createContentItem() {
        return new ContentItem();
    }

    /**
     * Create an instance of {@link RecordList }
     * 
     */
    public RecordList createRecordList() {
        return new RecordList();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ContentItemList }
     * 
     */
    public ContentItemList createContentItemList() {
        return new ContentItemList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content/2008", name = "ContentItem")
    public JAXBElement<ContentItem> createContentItem(ContentItem value) {
        return new JAXBElement<ContentItem>(_ContentItem_QNAME, ContentItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content/2008", name = "RecordList", scope = Property.class)
    public JAXBElement<RecordList> createPropertyRecordList(RecordList value) {
        return new JAXBElement<RecordList>(_PropertyRecordList_QNAME, RecordList.class, Property.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content/2008", name = "String", scope = Property.class)
    public JAXBElement<String> createPropertyString(String value) {
        return new JAXBElement<String>(_PropertyString_QNAME, String.class, Property.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content/2008", name = "ContentItem", scope = Property.class)
    public JAXBElement<ContentItem> createPropertyContentItem(ContentItem value) {
        return new JAXBElement<ContentItem>(_ContentItem_QNAME, ContentItem.class, Property.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentItemList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://endeca.com/schema/content/2008", name = "ContentItemList", scope = Property.class)
    public JAXBElement<ContentItemList> createPropertyContentItemList(ContentItemList value) {
        return new JAXBElement<ContentItemList>(_PropertyContentItemList_QNAME, ContentItemList.class, Property.class, value);
    }

}
