//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.17 at 02:15:09 PM CDT 
//


package com.kp.content.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * <p>Java class for Property complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Property">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="String" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Boolean" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RecordList" type="{http://endeca.com/schema/content/2008}RecordList"/>
 *         &lt;element name="ContentItem" type="{http://endeca.com/schema/content/2008}ContentItem"/>
 *         &lt;element name="ContentItemList" type="{http://endeca.com/schema/content/2008}ContentItemList"/>
 *         &lt;any processContents='lax' namespace='##other'/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Property", propOrder = {
    "string",
    "_boolean",
    "recordList",
    "contentItem",
    "contentItemList",
    "any"
})
public class Property {

    @XmlElementRef(name = "String", namespace = "http://endeca.com/schema/content/2008", type = JAXBElement.class, required = false)
    protected JAXBElement<String> string;
    @XmlElement(name = "Boolean")
    protected String _boolean;
    @XmlElementRef(name = "RecordList", namespace = "http://endeca.com/schema/content/2008", type = JAXBElement.class, required = false)
    protected JAXBElement<RecordList> recordList;
    @XmlElementRef(name = "ContentItem", namespace = "http://endeca.com/schema/content/2008", type = JAXBElement.class, required = false)
    protected JAXBElement<ContentItem> contentItem;
    @XmlElementRef(name = "ContentItemList", namespace = "http://endeca.com/schema/content/2008", type = JAXBElement.class, required = false)
    protected JAXBElement<ContentItemList> contentItemList;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "Name")
    protected String name;

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setString(JAXBElement<String> value) {
        this.string = value;
    }

    /**
     * Gets the value of the boolean property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoolean() {
        return _boolean;
    }

    /**
     * Sets the value of the boolean property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoolean(String value) {
        this._boolean = value;
    }

    /**
     * Gets the value of the recordList property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RecordList }{@code >}
     *     
     */
    public JAXBElement<RecordList> getRecordList() {
        return recordList;
    }

    /**
     * Sets the value of the recordList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RecordList }{@code >}
     *     
     */
    public void setRecordList(JAXBElement<RecordList> value) {
        this.recordList = value;
    }

    /**
     * Gets the value of the contentItem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ContentItem }{@code >}
     *     
     */
    public JAXBElement<ContentItem> getContentItem() {
        return contentItem;
    }

    /**
     * Sets the value of the contentItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ContentItem }{@code >}
     *     
     */
    public void setContentItem(JAXBElement<ContentItem> value) {
        this.contentItem = value;
    }

    /**
     * Gets the value of the contentItemList property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ContentItemList }{@code >}
     *     
     */
    public JAXBElement<ContentItemList> getContentItemList() {
        return contentItemList;
    }

    /**
     * Sets the value of the contentItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ContentItemList }{@code >}
     *     
     */
    public void setContentItemList(JAXBElement<ContentItemList> value) {
        this.contentItemList = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
