//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.07 at 01:10:40 PM CDT 
//


package com.kp.dimensions.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DVAL"/>
 *         &lt;element ref="{}DIMENSION_NODE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dval",
    "dimensionnode"
})
@XmlRootElement(name = "DIMENSION_NODE")
public class DIMENSIONNODE {

    @XmlElement(name = "DVAL", required = true)
    protected DVAL dval;
    @XmlElement(name = "DIMENSION_NODE")
    protected List<DIMENSIONNODE> dimensionnode;

    /**
     * Gets the value of the dval property.
     * 
     * @return
     *     possible object is
     *     {@link DVAL }
     *     
     */
    public DVAL getDVAL() {
        return dval;
    }

    /**
     * Sets the value of the dval property.
     * 
     * @param value
     *     allowed object is
     *     {@link DVAL }
     *     
     */
    public void setDVAL(DVAL value) {
        this.dval = value;
    }

    /**
     * Gets the value of the dimensionnode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dimensionnode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDIMENSIONNODE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DIMENSIONNODE }
     * 
     * 
     */
    public List<DIMENSIONNODE> getDIMENSIONNODE() {
        if (dimensionnode == null) {
            dimensionnode = new ArrayList<DIMENSIONNODE>();
        }
        return this.dimensionnode;
    }

}
