//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.07 at 01:10:40 PM CDT 
//


package com.kp.dimensions.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DIMENSION_ID"/>
 *         &lt;element ref="{}DIMENSION_NODE"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SRC_TYPE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="INTERNAL"/>
 *             &lt;enumeration value="PROPMAPPER"/>
 *             &lt;enumeration value="AUTOGEN"/>
 *             &lt;enumeration value="EXTERNAL"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SRC_FILE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dimensionid",
    "dimensionnode"
})
@XmlRootElement(name = "DIMENSION")
public class DIMENSION {

    @XmlElement(name = "DIMENSION_ID", required = true)
    protected DIMENSIONID dimensionid;
    @XmlElement(name = "DIMENSION_NODE", required = true)
    protected DIMENSIONNODE dimensionnode;
    @XmlAttribute(name = "NAME")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "SRC_TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String srctype;
    @XmlAttribute(name = "SRC_FILE")
    @XmlSchemaType(name = "anySimpleType")
    protected String srcfile;

    /**
     * Gets the value of the dimensionid property.
     * 
     * @return
     *     possible object is
     *     {@link DIMENSIONID }
     *     
     */
    public DIMENSIONID getDIMENSIONID() {
        return dimensionid;
    }

    /**
     * Sets the value of the dimensionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link DIMENSIONID }
     *     
     */
    public void setDIMENSIONID(DIMENSIONID value) {
        this.dimensionid = value;
    }

    /**
     * Gets the value of the dimensionnode property.
     * 
     * @return
     *     possible object is
     *     {@link DIMENSIONNODE }
     *     
     */
    public DIMENSIONNODE getDIMENSIONNODE() {
        return dimensionnode;
    }

    /**
     * Sets the value of the dimensionnode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DIMENSIONNODE }
     *     
     */
    public void setDIMENSIONNODE(DIMENSIONNODE value) {
        this.dimensionnode = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the srctype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRCTYPE() {
        return srctype;
    }

    /**
     * Sets the value of the srctype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRCTYPE(String value) {
        this.srctype = value;
    }

    /**
     * Gets the value of the srcfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRCFILE() {
        return srcfile;
    }

    /**
     * Sets the value of the srcfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRCFILE(String value) {
        this.srcfile = value;
    }

}
