//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.07 at 01:10:40 PM CDT 
//


package com.kp.dimensions.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DVAL_ID"/>
 *         &lt;element ref="{}SYN" maxOccurs="unbounded"/>
 *         &lt;element ref="{}LBOUND" minOccurs="0"/>
 *         &lt;element ref="{}UBOUND" minOccurs="0"/>
 *         &lt;element ref="{}PROP" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TYPE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="EXACT"/>
 *             &lt;enumeration value="RANGE"/>
 *             &lt;enumeration value="LEVEL"/>
 *             &lt;enumeration value="SIFT"/>
 *             &lt;enumeration value="DVAL"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dvalid",
    "syn",
    "lbound",
    "ubound",
    "prop"
})
@XmlRootElement(name = "DVAL")
public class DVAL {

    @XmlElement(name = "DVAL_ID", required = true)
    protected DVALID dvalid;
    @XmlElement(name = "SYN", required = true)
    protected List<SYN> syn;
    @XmlElement(name = "LBOUND")
    protected BOUNDC lbound;
    @XmlElement(name = "UBOUND")
    protected BOUNDC ubound;
    @XmlElement(name = "PROP")
    protected List<PROP> prop;
    @XmlAttribute(name = "TYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the dvalid property.
     * 
     * @return
     *     possible object is
     *     {@link DVALID }
     *     
     */
    public DVALID getDVALID() {
        return dvalid;
    }

    /**
     * Sets the value of the dvalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link DVALID }
     *     
     */
    public void setDVALID(DVALID value) {
        this.dvalid = value;
    }

    /**
     * Gets the value of the syn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the syn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSYN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYN }
     * 
     * 
     */
    public List<SYN> getSYN() {
        if (syn == null) {
            syn = new ArrayList<SYN>();
        }
        return this.syn;
    }

    /**
     * Gets the value of the lbound property.
     * 
     * @return
     *     possible object is
     *     {@link BOUNDC }
     *     
     */
    public BOUNDC getLBOUND() {
        return lbound;
    }

    /**
     * Sets the value of the lbound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BOUNDC }
     *     
     */
    public void setLBOUND(BOUNDC value) {
        this.lbound = value;
    }

    /**
     * Gets the value of the ubound property.
     * 
     * @return
     *     possible object is
     *     {@link BOUNDC }
     *     
     */
    public BOUNDC getUBOUND() {
        return ubound;
    }

    /**
     * Sets the value of the ubound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BOUNDC }
     *     
     */
    public void setUBOUND(BOUNDC value) {
        this.ubound = value;
    }

    /**
     * Gets the value of the prop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPROP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PROP }
     * 
     * 
     */
    public List<PROP> getPROP() {
        if (prop == null) {
            prop = new ArrayList<PROP>();
        }
        return this.prop;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPE(String value) {
        this.type = value;
    }

}
